name: Tridiemtri
version: '${project.version}'
main: id.forgeforce.tridiemtri.Tridiemtri
load: STARTUP
authors: [ CardanaMH ]
api-version: 1.17
commands:
  tridiemtri:
    description: "dapatkan 3DM MK 3"
    usage: /tridiemtri